### ISSUE TITLE
Google Drive Links for Model Download

### ISSUE THREAD

**Issue by monurcank** [Z-Xiong/OSTrack-mnn#2]
I'm truly impressed by your exceptional work in converting and sharing your models. Your contributions are undoubtedly valuable to the AI and machine learning community.

However, I've encountered difficulty accessing your models on Baidu due to geographical restrictions from Europe.

I kindly request that you consider uploading your models to more accessible platforms such as Google Drive or Github Release Assets. This would allow enthusiasts from regions like Europe to benefit from your work.

Thank you for your contributions and understanding.

**Comment by Z-Xiong** [comment]
Thanks for your attention to this work. I will upload models to Google Drive tomorrow.

**Comment by Z-Xiong** [comment]
The model has been uploaded, you can try to download the model and run ostrack. If you encounter any problems, you can give me feedback.

**Comment by ozgyal** [comment]
Hello, could you share your PyTorch to onnx conversion code piece? As I understand ostrack-256-ep300.onnx does not contain LayerNorm() which I intend to do with my model as well (due to an old tensorrt version). It would be really useful. I appreciate any help you can provide.

**Comment by Z-Xiong** [comment]
> Hello, could you share your PyTorch to onnx conversion code piece? As I understand ostrack-256-ep300.onnx does not contain LayerNorm() which I intend to do with my model as well (due to an old tensorrt version). It would be really useful. I appreciate any help you can provide.

Thank you for your interest in this project. I will upload the code next Monday.
